name: Adf-deployment

on:
  workflow_dispatch:

permissions:  
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ./  # Checkout to the root directory

    - name: Build ARM Template
      run: |
        # Add commands to build your ARM template here

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ./  # Checkout to the root directory

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        region: East US
        resourceGroupName: ${{ secrets.RESOURCE_GROUP}}
        template: Datafactory/template/adf-sql-wf.bicep
