name: Azure-data-migrationsS

on:
  push:
permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Use Azure PowerShell
        uses: azure/powershell@v1
        with:
          azPSVersion: '3.0.0'
          inlineScript: |
            $names = az datafactory trigger list --factory-name "myappadfa" --resource-group "project-dev" --query "[?properties.runtimeState=='Stopped'].name" -o tsv --only-show-errors
            foreach($name in $names){
              az datafactory trigger start --factory-name "myappadfa" --resource-group "project-dev" --name $name --only-show-errors
            }
