name: pwsh-trigger

on:
   push:

env:
  SCRIPT_PATH: 'azure-data-fatory/Template/script.ps2'
  RESOURCE_GROUP: 'project-dev'
  LOCATION: 'East US'

permissions:
    id-token: write
    contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
       
      - name: Run PowerShell Script
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            .\${{ env.SCRIPT_PATH }} -ResourceGroupName ${{ env.RESOURCE_GROUP }} -dataFactoryName 'myappadfa'
          azPSVersion: latest