name: delete-adf-resource

on:
  push:
permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Azure CLI script with PowerShell
        run: |
          $DataFactoryName = "myappdev"
          $ResourceGroupName = "project-dev"

          echo "Deploying Azure Data Factory resources..."

          # Run PowerShell script using Azure VM run-command
          az vm run-command invoke --command-id RunPowerShellScript --name YourVMName --resource-group project-dev --scripts ./azure-data-factory/Template/script.ps1

          echo "Deployment completed."

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
