name: Azure-data-migrationsS

on:
   workflow_dispatch:
permissions:
    id-token: write
    contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Run PowerShell script
        id: deploy
        run: |
          $ErrorActionPreference = "Stop"

          # Define parameters
          $DataFactoryName = ${{ secrets.DATA_FACTORY_NAME }}
          $DataFactoryResourceGroup = ${{ secrets.DATA_FACTORY_RESOURCE_GROUP }}
          $DataFactorySubscriptionId = ${{ secrets.DATA_FACTORY_SUBSCRIPTION_ID }}
          $DisableAllTriggers = ${{ secrets.DISABLE_ALL_TRIGGERS }}
          $EnabledTriggers = ${"daily_trigger"}

          # Add other required secrets here...

          # Rest of the PowerShell script (assuming the script is in the root directory)
          .\your_script.ps1 -DataFactoryName $DataFactoryName `
                             -DataFactoryResourceGroup $DataFactoryResourceGroup `
                             -DataFactorySubscriptionId $DataFactorySubscriptionId `
                             -DisableAllTriggers $DisableAllTriggers `
                             -EnabledTriggers $EnabledTriggers

      - name: Display script output
        run: |
          echo "${{ steps.deploy.outputs.stdout }}"
          echo "${{ steps.deploy.outputs.stderr }}"
