name: pwsh-trigger-start

on:
  workflow_dispatch:


env:
  SCRIPT_PATH: 'azure-data-fatory/Template/script.ps2'
  RESOURCE_GROUP: 'project-dev'
  LOCATION: 'East US'

permissions:
      id-token: write
      contents: read  

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Run PowerShell Script
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            .\${{ env.SCRIPT_PATH }} -ResourceGroupName ${{ env.RESOURCE_GROUP }} -dataFactoryName 'myappadfa'
          azPSVersion: latest
