name: delete-dataset-adf
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      

      # Delete Azure Data Factory Dataset
      - name: Delete Azure Data Factory Dataset
        run: |
          az datafactory dataset delete --myappadf Azure-data-migrationsS --resource-group ${{secrets.RESOURCE_GROUP}} --name ds_sqlrais
        
