name: delete-adf-resource

on:
  push:
permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Azure PowerShell
        uses: azure/setup-powershell@v1.1.0
        with:
          azPSVersion: 'latest'

      - name: Execute PowerShell script
        run: |
          $DataFactoryName = "myappdev"
          $ResourceGroupName = "project-dev"

          Write-Host "Deploying Azure Data Factory resources..."

          ./azure-data-factory/Template/script.ps1

          Write-Host "Deployment completed."

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
