name: powershell-deployment

on:
  push:
permissions:
      id-token: write
      contents: read

jobs:
  deploy-and-delete-adf:
    runs-on: windows-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy using PowerShell script
        shell: pwsh
        run: |
          azure-data-fatory/Template/script.ps1

      
