name: adf-RAIS-Data migrations

on:
  push:
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

       # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      # Deploy ARM template
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          region: East US
          resourceGroupName: ${{secrets.RESOURCE_GROUP}}
          #template: azure-data-fatory/Template/adf-copy.-working-code.bicep
          #parameters: ${{secrets.parametersFile}} sqlsourceUserId=${{secrets.SQLSOURCEUSERID}} sqlsourcePassword=${{secrets.SQLSOURCEPASSWORD}} sqlsinkUserId=${{secrets.SQLSINKUSERID}} sqlsinkPassword=${{secrets.SQLSINKPASSWORD}} sourceSqlServer=${{secrets.SOURCESQLSERVER}} sinkSqlServer=${{secrets.SINKSQLSERVER}} 

      # Use Azure PowerShell
      - name: Use Azure PowerShell
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            $names = az datafactory trigger list --factory-name "myappadfa" --resource-group "project-dev" --query "[?properties.runtimeState=='Started'].name" -o tsv --only-show-errors
            foreach($name in $names){
              az datafactory trigger start --factory-name "myappadfa" --resource-group "project-dev" --name $name --only-show-errors
            }
