name: pwsh-trigger

on:
  push:

env:
  SCRIPT_PATH: 'azure-data-factory/Template/script.ps1'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
       
      - name: Enable certain triggers and disable rest
        uses: azure/powershell@v1
        with:
          inlineScript: |
            # Content of your SetTriggers.ps1 script
            param(
                [string]$DataFactoryName,
                [string]$DataFactoryResourceGroup,
                [string]$DataFactorySubscriptionId,
                [bool]$DisableAllTriggers,
                [string]$EnabledTriggers
            )

            # Set your parameters
            $DataFactoryName = 'myappadfa'
            $DataFactoryResourceGroup = 'project-dev'
            $DataFactorySubscriptionId = '6cdd51be-69f2-4db8-ace0-61086685ec5c'
            $DisableAllTriggers = $true
            $EnabledTriggers = 'daily_trigger'

            .\$(env:SCRIPT_PATH) -DataFactoryName $DataFactoryName -DataFactoryResourceGroup $DataFactoryResourceGroup -DataFactorySubscriptionId $DataFactorySubscriptionId -DisableAllTriggers $DisableAllTriggers -EnabledTriggers $EnabledTriggers
