name: Delete-adf

on:
  workflow_dispatch:

env:

  SCRIPT_PATH: 'azure-data-factory/Template/script.ps1'  # set this to the correct path where your PowerShell code is stored.
  RESOURCE_GROUP: project-app
  LOCATION: 'East US'
   
permissions:
  id-token: write
  contents: read

jobs:
  login-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

  deploy-function:
    needs: login-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            azure-data-factory/Template/script.ps1 -FunctionName ${{ env.FUNCTION_NAME }} -FunctionResourceGroup ${{ env.RESOURCE_GROUP }} -Location ${{ env.LOCATION }}
          azPSVersion: latest
