on:
  push:
permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./  # Checkout to the root directory

      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
        # Optionally, add `audience` if required:
        # audience: <your-app-registration-client-id>

      - name: Verify Azure Credentials
        run: |
          Write-Host "Azure Credentials Secret Content:"
          Write-Host ${{secrets.AZURE_CREDENTIALS}}
          # Add more logging or checks as needed

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          pwsh: true  # Use PowerShell core
          inlineScript: |
            # Ensure script path and permissions are correct
            if (Test-Path -Path ./deployFA.ps1) {
              Write-Host "Script found. Executing..."
              ./deployFA.ps1 -FunctionName ${{ env.FUNCTION_NAME }} -FunctionResourceGroup ${{ env.RESOURCE_GROUP }} -Location ${{ env.LOCATION }}
            } else {
              Write-Host "Script not found at specified path."
              # Handle error or provide instructions to locate the script
            }
          azPSVersion: latest
