on:
  push:
    

name: AzurePowerShellSampleWithFile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 

      - name: Run Azure PowerShell Script File
        uses: azure/powershell@v1
        with:
          inlineScript: ./azure-data-factory/Template/script.ps1 myresourcegroup myresourcename
          azPSVersion: "latest"
