name: Remove Azure Data Factory Dataset

on:
  push:
    branches:
      - main

jobs:
  remove-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run PowerShell script
      shell: pwsh
      run: |
        Remove-AzureRmDataFactoryDataset -Force -DataFactoryName "myappadfa" -Name "ds_myazurcloud" -ResourceGroupName "project-dev"
