name : pws script

on:
  push:
    
jobs:
  build-and-deploy:
    name: run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: sctipt
        run: Write-Host 'hello,world'
        shell: pwsh