on: [push]

name: AzurePowerShellSampleWithFile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          enable-AzPSSession: true 
      - name: Run Azure PowerShell Script File
        uses: azure/powershell@v1
        with:
          inlineScript: ./azure-data-factory/Template/adf-copy-working-code.bicep myresourcegroup myresourcename
          azPSVersion: "latest"
