name: powershell-deployments

on:
  workflow_dispatch:
    permissions:
      id-token: write
      contents: read

env:
  FUNCTION_NAME: 4besghactions2
  SCRIPT_PATH: 'azure-data-fatory/scripts.ps1'
  RESOURCE_GROUP: project-app
  LOCATION: 'East US'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            .\azure-data-factory/scripts.ps1 -FunctionName ${{ env.FUNCTION_NAME }} -FunctionResourceGroup ${{ env.RESOURCE_GROUP }} -Location ${{ env.LOCATION }}
          azPSVersion: latest
